apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-development-tenant
  namespace: threescale-development
spec:
  email: dev@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: openshift-operators
  organizationName: development
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: openshift-operators
  systemMasterUrl: 'https://master.apps.labtools.lab.psi.pnq2.redhat.com'
  tenantSecretRef:
    name: tenant-secret
  username: admin
