apiVersion: capabilities.3scale.net/v1alpha1
kind: Tenant
metadata:
  name: threescale-testing-tenant
  namespace: threescale-testing
spec:
  email: test@example.openshift.com
  masterCredentialsRef:
    name: system-seed
    namespace: openshift-operators
  organizationName: testing
  passwordCredentialsRef:
    name: tenant-admin-secret
    namespace: openshift-operators
  systemMasterUrl: 'https://openshift-operators'
  tenantSecretRef:
    name: tenant-secret
  username: admin
